name: 1vs1
api: [3.0.0-ALPHA7]
version: 1.0.0 [DEV]
author: CzechPMDevs
authors: [GamakCZ]
description: Simple 1vs1 plugin for PocketMine
main: OneVsOne\Main

#commands:
#  1vs1:
#    description: 1vs1 commands

permissions:
  1vs1:
    description: All 1vs1 permissions
    default: op
    children:
      1vs1.cmd:
        description: All 1vs1 permissions for commands
        default: op
        children:
          1vs1.cmd.help:
            description: Permissions for /1vs1 help
            default: op
          1vs1.cmd.addarena:
            description: Permissions for /1vs1 addarena
            default: op


